Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:
  ##
  # Create the bucket to store the lambda code
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
