
Resources:
  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FreeDays_Account
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema: 
        - AttributeName: username
          KeyType: HASH

  SymbolHistoryConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FreeDays_SymbolHistoryConfig
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: symbol
          AttributeType: S
      KeySchema: 
        - AttributeName: type
          KeyType: HASH
        - AttributeName: symbol
          KeyType: RANGE