
Resources:
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FreeDays_Account
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: _id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema: 
        - AttributeName: _id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: Unique_username
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL