
Resources:
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FreeDays_Account
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: "_id"
          KeyType: HASH