
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  ZipFileName:
    Type: String
    Description: The name of the zip file which contains the lambda code

Resources:
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref BucketName
        ZipFileName: !Ref ZipFileName
      TemplateURL: ./api-gateway.yaml
