Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  ZipFileName:
    Type: String
    Description: The name of the zip file which contains the lambda code

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        Bucket: !Ref BucketName
        Key: !Ref ZipFileName
      Runtime: "nodejs14.x"
      Handler: out/controllers/stockHistoryManagement.patch_addStockToTrack
      Timeout: 10

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        swagger: 2.0
        info:
          version: 1.0.0
          title: FreeDays lambdas
        basePath: /api
        schemes:
          - https
      Name: FreeDaysLambdas
      Parameters:
        endpointConfigurationTypes: REGIONAL

  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !GetAtt RestApi.RootResourceId
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      Integration:
        Credentials: !GetAtt InvocationRole.Arn
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Join
          - "/"
          - - "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions"
            - !GetAtt Lambda.Arn
            - "invocations"

  InvocationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaRuntimePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  ##
  # List of lambdas
  Lambda1:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref BucketName
        ZipFileName: !Ref ZipFileName
        InvocationRoleArn: !GetAtt InvocationRole.Arn
        EntryPoint: stockHistoryManagement.patch_addStockToTrack
        HttpMethod: PATCH
      TemplateURL: ./lambda.yaml
