Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  ZipFileName:
    Type: String
    Description: The name of the zip file which contains the lambda code

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: FreeDaysLambdas
      Parameters:
        endpointConfigurationTypes: REGIONAL

  InvocationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaRuntimePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties: 
      DeploymentId: !Ref Deployment
      RestApiId: !Ref RestApi

  ##
  # List of lambdas
  StockHistoryManagementResource:
    Type: AWS::ApiGateway::Resource
    Properties: 
      ParentId: !Ref RestApiRootResourceId
      PathPart: stock-history-management
      RestApiId: !Ref RestApiId

  Lambda1:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref BucketName
        ZipFileName: !Ref ZipFileName
        RestApiId: !Ref RestApi
        InvocationRoleArn: !GetAtt InvocationRole.Arn
        RestApiRootResourceId: !Ref StockHistoryManagementResource
        EntryPoint: stockHistoryManagement.patch_addStockToTrack
        Path: add
        HttpMethod: PATCH
      TemplateURL: ./lambda.yaml
