Transform: 
  - AWS::Serverless-2016-10-31
  - Count

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  EntryPoints:
    Type: CommaDelimitedList
    Description: A comma delimited list of entry points
  NumEntryPoints:
    Type: Number
    Description: The number of entrypoints in the EntryPoints parameter

Resources:
  Lambda:
    Type: AWS::CloudFormation::Stack
    Count: 2
    Properties:
      TemplateURL: sgegs
      Parameters:
        BucketName: !Ref BucketName
        Handler: !Select
          - %d
          - !Ref EntryPoints
