Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  ZipFileName:
    Type: String
    Description: The name of the zip file which contains the lambda code

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        Bucket: !Ref BucketName
        Key: !Ref ZipFileName
      Runtime: "nodejs14.x"
      Handler: controllers/stockHistoryManagement.patch_addStockToTrack
      Timeout: 10

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        swagger: 2.0
        info:
          version: 1.0.0
          title: FreeDays lambdas
        basePath: /api
        schemes:
          - https
        definitions:
          Empty:
            type: object
      Name: FreeDaysLambdas
      Parameters:
        endpointConfigurationTypes: REGIONAL

