name: Site

on:
  push
  #push:
    #branches:
    #  - main
    #paths:
    #  - lambdas/**

jobs:
  create-s3:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Cloudformation Template
        run: |
          cd lambdas/cloudformation
          aws cloudformation deploy --template-file pre.yaml --stack-name financial-planning-lambdas-pre --capabilities CAPABILITY_NAMED_IAM --parameter-overrides \
            LambdaBucketName=${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code \
            CountBucketName=${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-count

  build-and-upload:
    runs-on: ubuntu-latest
    environment: main
    needs: 
      - create-s3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Other Dependencies
        run: |
          sudo npm i -g typescript

      - name: Build the lambdas
        run: |
          cd lambdas
          npm install
          tsc

      - name: Package
        run: |
          mkdir dist
          zip -r dist/lambdas.zip lambdas/out/* -i *.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code --size-only --delete

  setup-count-macro:
    runs-on: ubuntu-latest
    environment: main
    needs:
      - create-s3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: aws-cloudformation/aws-cloudformation-macros
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy macro
        run: |
          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket ${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-count \
            --output-template-file packaged.yaml
          aws cloudformation deploy \
            --stack-name financial-planning-lambdas-count \
            --template-file packaged.yaml \
            --capabilities CAPABILITY_IAM

      - name: Clean the s3 bucket
        run: |
          mkdir blankdir
          aws s3 sync ./blankdir s3://${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-count --delete

  deploy:
    runs-on: ubuntu-latest
    environment: main
    needs: 
      - build-and-upload
      - setup-count-macro
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare the template
        #https://github.com/aws-cloudformation/aws-cloudformation-macros/tree/master/Count
        run: |
          aws cloudformation package \
            --template-file main.yaml \
            --s3-bucket ${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code \
            --output-template-file packaged.yaml
          aws cloudformation deploy \
            --stack-name Count-macro \
            --template-file packaged.yaml \
            --capabilities CAPABILITY_IAM

      - name: Deploy Cloudformation Template
        run: |
          cd lambdas/cloudformation
          aws cloudformation deploy --template-file main.yaml --stack-name financial-planning-lambdas-main --capabilities CAPABILITY_NAMED_IAM --parameter-overrides \
            BucketName=${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code \
            EntryPoints=index.entry,index.entry2 \
            NumEntryPoints=2
