name: Site

on:
  push:
    branches:
      - main
    #paths:
    #  - lambdas/**

jobs:
  create-s3:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Cloudformation Template
        run: |
          cd lambdas/cloudformation
          aws cloudformation deploy --template-file pre.yaml --stack-name financial-planning-lambdas-pre --capabilities CAPABILITY_NAMED_IAM --parameter-overrides \
            BucketName=${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code

  build-and-upload:
    runs-on: ubuntu-latest
    environment: main
    needs: 
      - create-s3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Other Dependencies
        run: |
          sudo npm i -g typescript

      - name: Build the lambdas
        run: |
          cd lambdas
          tsc
          pwd
          ls out

      - name: Package
        run: |
          pwd
          ls out
          zip -r dist.zip out/* -i *.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact
        run: |
          aws s3 sync ./dist.zip s3://${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambdas-pre --size-only

  deploy:
    runs-on: ubuntu-latest
    environment: main
    needs: 
      - build-and-upload
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Cloudformation Template
        run: |
          cd lambdas/cloudformation
          aws cloudformation deploy --template-file main.yaml --stack-name financial-planning-lambdas-main --capabilities CAPABILITY_NAMED_IAM --parameter-overrides \
            BucketName=${{ secrets.AWS_ACCOUNT_ID }}-financial-planning-lambda-code
            EntryPoints=index.entry,index.entry2
            NumEntryPoints=2
