name: Site

on:
  push:
    branches:
      - main

jobs:
  create-s3:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Cloudformation Template
        run: |
          cd site
          aws cloudformation deploy --template-file cloudformation-pre.yaml --stack-name financial-planning-site-pre --capabilities CAPABILITY_NAMED_IAM

  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build the site
        run: |
          cd site
          gatsby build